kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: golang:1.14-alpine
  commands:
  - apk add git make
  - make examples --always-make
  - git diff --exit-code
